#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/reduce/vibedropper-go,github.com/stainless-sdks/vibedropper-go"

REPLACEMENT="${1:-"../vibedropper-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/reduce/vibedropper-go="$REPLACEMENT"
go mod tidy -e
